const Feedback = require('../models/Feedback');
const { sendEmail } = require('../services/emailService');
const { backendLogger } = require('../config/logger');

exports.submitFeedback = async (req, res) => {
    const { message } = req.body;
    const context = 'supportController.submitFeedback';
    const { correlation_id } = req;
    
    try {
        const newFeedback = new Feedback({
            message,
            user: req.user.id,
        });
        await newFeedback.save();

        const emailOptions = {
            to: process.env.SUPPORT_EMAIL || 'support@xpark.com',
            subject: `📩 Feedback from ${req.user.username}`,
            html: `
                <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
                    <h2 style="color: #2c3e50;">New User Feedback Received</h2>
                    <p><strong>User:</strong> ${req.user.username} (${req.user.email})</p>
                    <p><strong>Message:</strong></p>
                    <blockquote style="border-left: 4px solid #3498db; margin: 1em 0; padding: 0.5em 1em; background: #f9f9f9;">
                        ${message}
                    </blockquote>
                    <hr />
                    <p style="font-size: 12px; color: #777;">This message was automatically generated by XPark Feedback System.</p>
                </div>
            `
        };

        await sendEmail(emailOptions);

        backendLogger.success('Feedback submitted successfully by user.', { context, correlation_id, details: { userId: req.user.id } });
        res.status(201).json({ msg: 'Feedback submitted successfully. Thank you!' });

    } catch (err) {
        backendLogger.error("Error submitting feedback.", { context, correlation_id, details: { userId: req.user.id, error: err.message, stack: err.stack } });
        res.status(500).json({ msg: 'Server error. Please try again later.' });
    }
};